$axure.loadCurrentPage({
  "url":"病虫管理.html",
  "generationDate":new Date(1423878327484.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"level",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"a9b18ff0a94448559aa8b279e3be52d8",
    "type":"Axure:Page",
    "name":"病虫管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});