$axure.loadCurrentPage({
  "url":"测报点管理.html",
  "generationDate":new Date(1423878330920.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"level",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"973f476c3aae471583039a309a3b2825",
    "type":"Axure:Page",
    "name":"测报点管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});