$axure.loadCurrentPage({
  "url":"系统设置.html",
  "generationDate":new Date(1423878336999.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"level",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"645a485d588e4a5585f64fdd33a2c7ee",
    "type":"Axure:Page",
    "name":"系统设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});